#:mute

#:include '../src/macros/dnad_dual_types.fypp'
#:include '../src/macros/dnad_getters.fypp'
#:include '../src/macros/dnad_overload_interfaces.fypp'
#:include '../src/macros/dnad_overload_implementations.fypp'
#:include '../src/macros/dnad_initialize.fypp'

#! When stringent = False, the dnad functions assume that the derivative exists. It is does not exist (for instance for abs(0.0))
#! the result will be undefined. When stringent = True (or not defined) some logic is included in the mathematical functions to
#! determine if the derivative exists of not, and call a function set_NaN() when it does not exist. Using stringent = False is 
#! believed to be faster.
#:set stringent = True

#! selected_interfaces is a comma separated list or "--all"
#:set selected_interfaces = "=,+,acos"

#:endmute
module example_dual_undef_mod
    use, intrinsic :: iso_fortran_env, only: dp => real64
    implicit none

    private
    public :: example_dual_undef

    integer, parameter :: num_deriv = 3 ! Number of derivatives

  #:if stringent
    ! Workaround to make pure functions produce NaN's deliberately:
    real(dp) :: negative_one = -1.0_dp
  #:endif
    
    #! Inject the dual type definitions
    #!  Note: Calling a macro with @ will convert all arguments to strings
    @:dnad_dual_type(uvw, dp, num_deriv, sequence)
    $:dnad_getter_interfaces(["uvw"])

    #! Inject interfaces
    #!  Note: Calling a macro with $ will send in python variables as arguments
    $:dnad_initialize_interface(["uvw"])
    $:dnad_overload_interfaces(["uvw"], selected_interfaces)
    
contains

    subroutine example_dual_undef()

        type(dual__uvw_t) :: uhd, vhd, whd, fhd

        call initialize(uhd, 1.0_dp, 1)
        call initialize(vhd, 1.0_dp, 2)
        call initialize(whd, 1.0_dp, 3)

        ! Function to compute value, gradient and Hessian for:
        fhd = test_function(uhd, vhd, whd)


        print *, "Function value:"
        print *, fvalue(fhd)

        print *, "Gradient:"
        print *, gradient(fhd)

    end subroutine

    elemental function test_function(u, v, w) result(f)
        type(dual__uvw_t), intent(in) :: u, v, w
        type(dual__uvw_t) :: f
        f = acos(u)
    end function

    #! Inject overloaded function implementations
    $:dnad_getter_implementations(["uvw"], "dp")
    $:dnad_initialize_implementations(["uvw"], "dp")
    $:dnad_overload_implementations(["uvw"], "dp", selected_interfaces=selected_interfaces, stringent=stringent)
    
  #:if stringent
    ! Workaround to make pure functions produce NaN's deliberately:
    elemental function set_NaN() result(res)
        real(dp) :: res
        res = sqrt(negative_one)
    end function set_NaN
  #:endif
    
end module