
#:def add_d(dual_type, dual_sn, real_kind, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function add__${dual_sn}$(u) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$) :: res
        
        res%f = u%f
        res%g = u%g
      #:if test_coverage
        add__d_counter = add__d_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function add__${dual_sn}$_${dual_sn}$(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u%f + v%f
        res%g = u%g + v%g
      #:if test_coverage
        add__d_d_counter = add__d_d_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function add__${dual_sn}$_r(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        real(${real_kind}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u%f + v
        res%g = u%g
      #:if test_coverage
        add__d_r_counter = add__d_r_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function add__r_${dual_sn}$(u, v) result(res)
        real(${real_kind}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u + v%f
        res%g = v%g
      #:if test_coverage
        add__r_d_counter = add__r_d_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function add__${dual_sn}$_i(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        integer, intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u%f + v
        res%g = u%g
      #:if test_coverage
        add__d_i_counter = add__d_i_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function add__i_${dual_sn}$(u, v) result(res)
        integer, intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u + v%f
        res%g = v%g
      #:if test_coverage
        add__i_d_counter = add__i_d_counter + 1
      #:endif
    end function
#:enddef

#:def add_hd(dual_type, dual_sn, real_kind, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function add__${dual_sn}$(u) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$) :: res
        
        res%d%f = u%d%f
        res%d%g = u%d%g
        res%h = u%h
      #:if test_coverage
        add__hd_counter = add__hd_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function add__${dual_sn}$_${dual_sn}$(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%d%f = u%d%f + v%d%f
        res%d%g = u%d%g + v%d%g
        res%h = u%h + v%h
      #:if test_coverage
        add__hd_hd_counter = add__hd_hd_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function add__${dual_sn}$_r(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        real(${real_kind}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%d%f = u%d%f + v
        res%d%g = u%d%g
        res%h = u%h
      #:if test_coverage
        add__hd_r_counter = add__hd_r_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function add__r_${dual_sn}$(u, v) result(res)
        real(${real_kind}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%d%f = u + v%d%f
        res%d%g = v%d%g
        res%h = v%h
      #:if test_coverage
        add__r_hd_counter = add__r_hd_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function add__${dual_sn}$_i(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        integer, intent(in) :: v
        type(${dual_type}$) :: res
        
        res%d%f = u%d%f + v
        res%d%g = u%d%g
        res%h = u%h
      #:if test_coverage
        add__hd_i_counter = add__hd_i_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function add__i_${dual_sn}$(u, v) result(res)
        integer, intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%d%f = u + v%d%f
        res%d%g = v%d%g
        res%h = v%h
      #:if test_coverage
        add__i_hd_counter = add__i_hd_counter + 1
      #:endif
    end function
#:enddef

