#:def assign_d(dual_type, dual_sn, real_kind, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ subroutine assign__${dual_sn}$_i(u, i)
        type(${dual_type}$), intent(out) :: u
        integer, intent(in) :: i

        u%f = real(i, ${real_kind}$)  ! This is faster than direct assignment
        u%g = 0.0_${real_kind}$
      #:if test_coverage
        assign__d_i_counter = assign__d_i_counter + 1
      #:endif

    end subroutine
    ${elemental_purity}$ subroutine assign__${dual_sn}$_r(u, r)
        type(${dual_type}$), intent(out) :: u
        real(${real_kind}$), intent(in) :: r

        u%f = r
        u%g = 0.0_${real_kind}$
      #:if test_coverage
        assign__d_r_counter = assign__d_r_counter + 1
      #:endif

    end subroutine
    ${elemental_purity}$ subroutine assign__i_${dual_sn}$(i, v)
        type(${dual_type}$), intent(in) :: v
        integer, intent(out) :: i

        i = int(v%f)
      #:if test_coverage
        assign__i_d_counter = assign__i_d_counter + 1
      #:endif

    end subroutine
    ${elemental_purity}$ subroutine assign__r_${dual_sn}$(r, v)
        type(${dual_type}$), intent(in) :: v
        real(${real_kind}$), intent(out) :: r

        r = v%f
      #:if test_coverage
        assign__r_d_counter = assign__r_d_counter + 1
      #:endif

    end subroutine
#:enddef

#:def assign_hd(dual_type, dual_sn, real_kind, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ subroutine assign__${dual_sn}$_i(u, i)
        type(${dual_type}$), intent(out) :: u
        integer, intent(in) :: i

        u%d%f = real(i, ${real_kind}$)  ! This is faster than direct assignment
        u%d%g = 0.0_${real_kind}$
        u%h = 0.0_${real_kind}$
      #:if test_coverage
        assign__hd_i_counter = assign__hd_i_counter + 1
      #:endif

    end subroutine
    ${elemental_purity}$ subroutine assign__${dual_sn}$_r(u, r)
        type(${dual_type}$), intent(out) :: u
        real(${real_kind}$), intent(in) :: r

        u%d%f = r
        u%d%g = 0.0_${real_kind}$
        u%h = 0.0_${real_kind}$
      #:if test_coverage
        assign__hd_r_counter = assign__hd_r_counter + 1
      #:endif

    end subroutine
    ${elemental_purity}$ subroutine assign__i_${dual_sn}$(i, v)
        type(${dual_type}$), intent(in) :: v
        integer, intent(out) :: i

        i = int(v%d%f)
      #:if test_coverage
        assign__i_hd_counter = assign__i_hd_counter + 1
      #:endif

    end subroutine
    ${elemental_purity}$ subroutine assign__r_${dual_sn}$(r, v)
        type(${dual_type}$), intent(in) :: v
        real(${real_kind}$), intent(out) :: r

        r = v%d%f
      #:if test_coverage
        assign__r_hd_counter = assign__r_hd_counter + 1
      #:endif

    end subroutine
#:enddef
