
#:def log_d(dual_type, dual_sn, real_kind, size_dx, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function log_${dual_sn}$(u) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$) :: res
        
        res%f = log(u%f)
        res%g = u%g/u%f
      #:if test_coverage
        log_d_counter = log_d_counter + 1
      #:endif
    end function
#:enddef

#:def log_hd(dual_type, dual_sn, real_kind, size_dx, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function log_${dual_sn}$(u) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$) :: res
        integer :: i, j, k
        real(${real_kind}$) :: t0
        
        t0 = 1.0_${real_kind}$/u%f
        res%f = log(u%f)
        res%g = t0*u%g
        k = 0
        do j = 1, ${size_dx}$
            do i = j, ${size_dx}$
                k = k + 1
                res%h(k) = t0*(-t0*u%g(i)*u%g(j) + u%h(k))
            end do
        end do
      #:if test_coverage
        log_hd_counter = log_hd_counter + 1
      #:endif
    end function
#:enddef

