
#:def lt(dual_type, dual_sn, real_kind, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$  function lt__${dual_sn}$_${dual_sn}$(lhs, rhs) result(res)
         type(${dual_type}$), intent(in) :: lhs, rhs
         logical :: res

         res = (lhs%f < rhs%f)

    end function
    ${elemental_purity}$  function lt__${dual_sn}$_i(lhs, rhs) result(res)
         type(${dual_type}$), intent(in) :: lhs
         integer, intent(in) :: rhs
         logical :: res

         res = (lhs%f < rhs)

    end function
    ${elemental_purity}$  function lt__${dual_sn}$_r(lhs, rhs) result(res)
         type(${dual_type}$), intent(in) :: lhs
         real(${real_kind}$), intent(in) :: rhs
         logical :: res

         res = (lhs%f < rhs)

    end function
    ${elemental_purity}$  function lt__i_${dual_sn}$(lhs, rhs) result(res)
         integer, intent(in) :: lhs
         type(${dual_type}$), intent(in) :: rhs
         logical :: res

         res = (lhs < rhs%f)

    end function
    ${elemental_purity}$  function lt__r_${dual_sn}$(lhs, rhs) result(res)
         real(${real_kind}$), intent(in) :: lhs
         type(${dual_type}$), intent(in) :: rhs
         logical :: res

         res = (lhs < rhs%f)

    end function
#:enddef
