
#:def minus_d(dual_type, dual_sn, real_kind, size_dx, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function unary_minus_${dual_sn}$(u) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$) :: res
        
        res%f = -u%f
        res%g = -u%g
      #:if test_coverage
        unary_minus_d_counter = unary_minus_d_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_${dual_sn}$_${dual_sn}$(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u%f - v%f
        res%g = u%g - v%g
      #:if test_coverage
        minus_d_d_counter = minus_d_d_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_${dual_sn}$_r(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        real(${real_kind}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u%f - v
        res%g = u%g
      #:if test_coverage
        minus_d_r_counter = minus_d_r_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_r_${dual_sn}$(u, v) result(res)
        real(${real_kind}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u - v%f
        res%g = -v%g
      #:if test_coverage
        minus_r_d_counter = minus_r_d_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_${dual_sn}$_i(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        integer, intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u%f - v
        res%g = u%g
      #:if test_coverage
        minus_d_i_counter = minus_d_i_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_i_${dual_sn}$(u, v) result(res)
        integer, intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u - v%f
        res%g = -v%g
      #:if test_coverage
        minus_i_d_counter = minus_i_d_counter + 1
      #:endif
    end function
#:enddef

#:def minus_hd(dual_type, dual_sn, real_kind, size_dx, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function unary_minus_${dual_sn}$(u) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$) :: res
        
        res%f = -u%f
        res%g = -u%g
        res%h = -u%h
      #:if test_coverage
        unary_minus_hd_counter = unary_minus_hd_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_${dual_sn}$_${dual_sn}$(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u%f - v%f
        res%g = u%g - v%g
        res%h = u%h - v%h
      #:if test_coverage
        minus_hd_hd_counter = minus_hd_hd_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_${dual_sn}$_r(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        real(${real_kind}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u%f - v
        res%g = u%g
        res%h = u%h
      #:if test_coverage
        minus_hd_r_counter = minus_hd_r_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_r_${dual_sn}$(u, v) result(res)
        real(${real_kind}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u - v%f
        res%g = -v%g
        res%h = -v%h
      #:if test_coverage
        minus_r_hd_counter = minus_r_hd_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_${dual_sn}$_i(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        integer, intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u%f - v
        res%g = u%g
        res%h = u%h
      #:if test_coverage
        minus_hd_i_counter = minus_hd_i_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_i_${dual_sn}$(u, v) result(res)
        integer, intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u - v%f
        res%g = -v%g
        res%h = -v%h
      #:if test_coverage
        minus_i_hd_counter = minus_i_hd_counter + 1
      #:endif
    end function
#:enddef

