
#:def mult_d(dual_type, dual_sn, real_kind, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function mult__${dual_sn}$_${dual_sn}$(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u%f*v%f
        res%g = u%g*v%f + u%f*v%g
      #:if test_coverage
        mult__d_d_counter = mult__d_d_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function mult__${dual_sn}$_r(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        real(${real_kind}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u%f*v
        res%g = u%g*v
      #:if test_coverage
        mult__d_r_counter = mult__d_r_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function mult__r_${dual_sn}$(u, v) result(res)
        real(${real_kind}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u*v%f
        res%g = u*v%g
      #:if test_coverage
        mult__r_d_counter = mult__r_d_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function mult__${dual_sn}$_i(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        integer, intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u%f*v
        res%g = u%g*v
      #:if test_coverage
        mult__d_i_counter = mult__d_i_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function mult__i_${dual_sn}$(u, v) result(res)
        integer, intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u*v%f
        res%g = u*v%g
      #:if test_coverage
        mult__i_d_counter = mult__i_d_counter + 1
      #:endif
    end function
#:enddef

#:def mult_hd(dual_type, dual_sn, real_kind, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function mult__${dual_sn}$_${dual_sn}$(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        integer :: i, j, k
        
        res%d%f = u%d%f*v%d%f
        res%d%g = u%d%g*v%d%f + u%d%f*v%d%g
        k = 0
        do j = 1, size(res%d%g)
            do i = j, size(res%d%g)
                k = k + 1
                res%h(k) = u%h(k)*v%d%f + u%d%g(i)*v%d%g(j) + u%d%g(j)*v%d%g(i) + u%d%f*v%h(k)
            end do
        end do
      #:if test_coverage
        mult__hd_hd_counter = mult__hd_hd_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function mult__${dual_sn}$_r(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        real(${real_kind}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%d%f = u%d%f*v
        res%d%g = u%d%g*v
        res%h = u%h*v
      #:if test_coverage
        mult__hd_r_counter = mult__hd_r_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function mult__r_${dual_sn}$(u, v) result(res)
        real(${real_kind}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%d%f = u*v%d%f
        res%d%g = u*v%d%g
        res%h = u*v%h
      #:if test_coverage
        mult__r_hd_counter = mult__r_hd_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function mult__${dual_sn}$_i(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        integer, intent(in) :: v
        type(${dual_type}$) :: res
        
        res%d%f = u%d%f*v
        res%d%g = u%d%g*v
        res%h = u%h*v
      #:if test_coverage
        mult__hd_i_counter = mult__hd_i_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function mult__i_${dual_sn}$(u, v) result(res)
        integer, intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%d%f = u*v%d%f
        res%d%g = u*v%d%g
        res%h = u*v%h
      #:if test_coverage
        mult__i_hd_counter = mult__i_hd_counter + 1
      #:endif
    end function
#:enddef

