
#:def pow_d(dual_type, dual_sn, real_kind, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function pow__${dual_sn}$_i(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        integer, intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u%f**v
        res%g = u%f**(v - 1)*u%g*v
      #:if test_coverage
        pow__d_i_counter = pow__d_i_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function pow__${dual_sn}$_r(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        real(${real_kind}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%f = u%f**v
        res%g = u%f**(v - 1)*u%g*v
      #:if test_coverage
        pow__d_r_counter = pow__d_r_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function pow__${dual_sn}$_${dual_sn}$(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        real(${real_kind}$) :: t0
        
        t0 = u%f**v%f
        res%f = t0
        res%g = t0*(u%g*v%f/u%f + v%g*log(u%f))

      #:if test_coverage
        pow__d_d_counter = pow__d_d_counter + 1
      #:endif
    end function
#:enddef

#:def pow_hd(dual_type, dual_sn, real_kind, is_pure, test_coverage, gdim = None)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function pow__${dual_sn}$_i(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        integer, intent(in) :: v
        type(${dual_type}$) :: res
      #:if gdim is None
        integer :: i, j, k
      #:endif
        
        res%d%f = u%d%f**v
        res%d%g = u%d%f**(v - 1)*v*u%d%g
      #:if gdim == 2
        res%h(1) = v*(u%d%g(1)*u%d%g(1)*(v - 1)*u%d%f**(v-2) + u%h(1)*u%d%f**(v-1))
        res%h(2) = v*(u%d%g(2)*u%d%g(1)*(v - 1)*u%d%f**(v-2) + u%h(2)*u%d%f**(v-1))
        res%h(3) = v*(u%d%g(2)*u%d%g(2)*(v - 1)*u%d%f**(v-2) + u%h(3)*u%d%f**(v-1))
      #:elif gdim == 3
        res%h(1) = v*(u%d%g(1)*u%d%g(1)*(v - 1)*u%d%f**(v-2) + u%h(1)*u%d%f**(v-1))
        res%h(2) = v*(u%d%g(2)*u%d%g(1)*(v - 1)*u%d%f**(v-2) + u%h(2)*u%d%f**(v-1))
        res%h(3) = v*(u%d%g(3)*u%d%g(1)*(v - 1)*u%d%f**(v-2) + u%h(3)*u%d%f**(v-1))
        res%h(4) = v*(u%d%g(2)*u%d%g(2)*(v - 1)*u%d%f**(v-2) + u%h(4)*u%d%f**(v-1))
        res%h(5) = v*(u%d%g(3)*u%d%g(2)*(v - 1)*u%d%f**(v-2) + u%h(5)*u%d%f**(v-1))
        res%h(6) = v*(u%d%g(3)*u%d%g(3)*(v - 1)*u%d%f**(v-2) + u%h(6)*u%d%f**(v-1))
      #:else
        k = 0
        do j = 1, size(res%d%g)
            do i = j, size(res%d%g)
                k = k + 1
                res%h(k) = v*(u%d%g(i)*u%d%g(j)*(v - 1)*u%d%f**(v-2) + u%h(k)*u%d%f**(v-1))
            end do
        end do
      #:endif
      #:if test_coverage
        pow__hd_i_counter = pow__hd_i_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function pow__${dual_sn}$_r(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        real(${real_kind}$), intent(in) :: v
        type(${dual_type}$) :: res
      #:if gdim is None
        integer :: i, j, k
      #:endif
        
        res%d%f = u%d%f**v
        res%d%g = u%d%f**(v - 1)*v*u%d%g
      #:if gdim == 2
        res%h(1) = v*(u%d%g(1)*u%d%g(1)*(v - 1)*u%d%f**(v-2) + u%h(1)*u%d%f**(v-1))
        res%h(2) = v*(u%d%g(2)*u%d%g(1)*(v - 1)*u%d%f**(v-2) + u%h(2)*u%d%f**(v-1))
        res%h(3) = v*(u%d%g(2)*u%d%g(2)*(v - 1)*u%d%f**(v-2) + u%h(3)*u%d%f**(v-1))
      #:elif gdim == 3
        res%h(1) = v*(u%d%g(1)*u%d%g(1)*(v - 1)*u%d%f**(v-2) + u%h(1)*u%d%f**(v-1))
        res%h(2) = v*(u%d%g(2)*u%d%g(1)*(v - 1)*u%d%f**(v-2) + u%h(2)*u%d%f**(v-1))
        res%h(3) = v*(u%d%g(3)*u%d%g(1)*(v - 1)*u%d%f**(v-2) + u%h(3)*u%d%f**(v-1))
        res%h(4) = v*(u%d%g(2)*u%d%g(2)*(v - 1)*u%d%f**(v-2) + u%h(4)*u%d%f**(v-1))
        res%h(5) = v*(u%d%g(3)*u%d%g(2)*(v - 1)*u%d%f**(v-2) + u%h(5)*u%d%f**(v-1))
        res%h(6) = v*(u%d%g(3)*u%d%g(3)*(v - 1)*u%d%f**(v-2) + u%h(6)*u%d%f**(v-1))
      #:else
        k = 0
        do j = 1, size(res%d%g)
            do i = j, size(res%d%g)
                k = k + 1
                res%h(k) = v*(u%d%g(i)*u%d%g(j)*(v - 1)*u%d%f**(v-2) + u%h(k)*u%d%f**(v-1))
            end do
        end do
      #:endif
      #:if test_coverage
        pow__hd_r_counter = pow__hd_r_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function pow__${dual_sn}$_${dual_sn}$(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
      #:if gdim is None
        integer :: i, j, k
      #:endif
        real(${real_kind}$) :: t0,t1,t2,t3
        
        t0 = u%d%f**v%d%f
        t1 = log(u%d%f)
        t2 = 1.0_${real_kind}$/u%d%f
        t3 = t1*v%d%f + 1
        res%d%f = t0
        res%d%g = t0*(t1*v%d%g + t2*u%d%g*v%d%f)

      #:if gdim == 2
        res%h(1) = t0*(t1*v%h(1) + t2*u%h(1)*v%d%f + t2*u%d%g(1)*(t2*u%d%g(1)*v%d%f*(v%d%f - 1) + t3*v%d%g(1)) + &
          v%d%g(1)*(t1**2*v%d%g(1) + t2*t3*u%d%g(1)))
        res%h(2) = t0*(t1*v%h(2) + t2*u%h(2)*v%d%f + t2*u%d%g(1)*(t2*u%d%g(2)*v%d%f*(v%d%f - 1) + t3*v%d%g(2)) + &
          v%d%g(1)*(t1**2*v%d%g(2) + t2*t3*u%d%g(2)))
        res%h(3) = t0*(t1*v%h(3) + t2*u%h(3)*v%d%f + t2*u%d%g(2)*(t2*u%d%g(2)*v%d%f*(v%d%f - 1) + t3*v%d%g(2)) + &
          v%d%g(2)*(t1**2*v%d%g(2) + t2*t3*u%d%g(2)))
      #:elif gdim == 3
        res%h(1) = t0*(t1*v%h(1) + t2*u%h(1)*v%d%f + t2*u%d%g(1)*(t2*u%d%g(1)*v%d%f*(v%d%f - 1) + t3*v%d%g(1)) + &
          v%d%g(1)*(t1**2*v%d%g(1) + t2*t3*u%d%g(1)))
        res%h(2) = t0*(t1*v%h(2) + t2*u%h(2)*v%d%f + t2*u%d%g(1)*(t2*u%d%g(2)*v%d%f*(v%d%f - 1) + t3*v%d%g(2)) + &
          v%d%g(1)*(t1**2*v%d%g(2) + t2*t3*u%d%g(2)))
        res%h(3) = t0*(t1*v%h(3) + t2*u%h(3)*v%d%f + t2*u%d%g(1)*(t2*u%d%g(3)*v%d%f*(v%d%f - 1) + t3*v%d%g(3)) + &
          v%d%g(1)*(t1**2*v%d%g(3) + t2*t3*u%d%g(3)))
        res%h(4) = t0*(t1*v%h(4) + t2*u%h(4)*v%d%f + t2*u%d%g(2)*(t2*u%d%g(2)*v%d%f*(v%d%f - 1) + t3*v%d%g(2)) + &
          v%d%g(2)*(t1**2*v%d%g(2) + t2*t3*u%d%g(2)))
        res%h(5) = t0*(t1*v%h(5) + t2*u%h(5)*v%d%f + t2*u%d%g(2)*(t2*u%d%g(3)*v%d%f*(v%d%f - 1) + t3*v%d%g(3)) + &
          v%d%g(2)*(t1**2*v%d%g(3) + t2*t3*u%d%g(3)))
        res%h(6) = t0*(t1*v%h(6) + t2*u%h(6)*v%d%f + t2*u%d%g(3)*(t2*u%d%g(3)*v%d%f*(v%d%f - 1) + t3*v%d%g(3)) + &
          v%d%g(3)*(t1**2*v%d%g(3) + t2*t3*u%d%g(3)))
      #:else
        k = 0
        do j = 1, size(res%d%g)
            do i = j, size(res%d%g)
                k = k + 1
                res%h(k) = t0*(t1*v%h(k) + t2*u%h(k)*v%d%f + t2*u%d%g(j)*(t2*u%d%g(i)*v%d%f*(v%d%f - &
      1) + t3*v%d%g(i)) + v%d%g(j)*(t1**2*v%d%g(i) + t2*t3*u%d%g(i)))
            end do
        end do
      #:endif
      #:if test_coverage
        pow__hd_hd_counter = pow__hd_hd_counter + 1
      #:endif
    end function
#:enddef

