
#:def pow_d(dual_type, dual_sn, real_kind, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function pow__${dual_sn}$_i(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        integer, intent(in) :: v
        type(${dual_type}$) :: res
        real(${real_kind}$) :: t0
        
        t0 = u%f**v
        res%f = t0
        res%g = t0*u%g*v/u%f
      #:if test_coverage
        pow_d_i_counter = pow_d_i_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function pow__${dual_sn}$_r(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        real(${real_kind}$), intent(in) :: v
        type(${dual_type}$) :: res
        real(${real_kind}$) :: t0
        
        t0 = u%f**v
        res%f = t0
        res%g = t0*u%g*v/u%f
      #:if test_coverage
        pow_d_r_counter = pow_d_r_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function pow__${dual_sn}$_${dual_sn}$(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        real(${real_kind}$) :: t0
        
        t0 = u%f**v%f
        res%f = t0
        res%g = t0*(u%g*v%f/u%f + v%g*log(u%f))
      #:if test_coverage
        pow_d_d_counter = pow_d_d_counter + 1
      #:endif
    end function
#:enddef

#:def pow_hd(dual_type, dual_sn, real_kind, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function pow__${dual_sn}$_i(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        integer, intent(in) :: v
        type(${dual_type}$) :: res
        integer :: i, j, k
        real(${real_kind}$) :: t0,t1,t2
        
        t0 = u%d%f**v
        t1 = 1.0_${real_kind}$/u%d%f
        t2 = t0*v
        res%d%f = t0
        res%d%g = t1*t2*u%d%g
        k = 0
        do j = 1, size(res%d%g)
            do i = j, size(res%d%g)
                k = k + 1
                res%h(k) = t1*t2*(t1*u%d%g(i)*u%d%g(j)*(v - 1) + u%h(k))
            end do
        end do
      #:if test_coverage
        pow_hd_i_counter = pow_hd_i_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function pow__${dual_sn}$_r(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        real(${real_kind}$), intent(in) :: v
        type(${dual_type}$) :: res
        integer :: i, j, k
        real(${real_kind}$) :: t0,t1,t2
        
        t0 = u%d%f**v
        t1 = 1.0_${real_kind}$/u%d%f
        t2 = t0*v
        res%d%f = t0
        res%d%g = t1*t2*u%d%g
        k = 0
        do j = 1, size(res%d%g)
            do i = j, size(res%d%g)
                k = k + 1
                res%h(k) = t1*t2*(t1*u%d%g(i)*u%d%g(j)*(v - 1) + u%h(k))
            end do
        end do
      #:if test_coverage
        pow_hd_r_counter = pow_hd_r_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function pow__${dual_sn}$_${dual_sn}$(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        integer :: i, j, k
        real(${real_kind}$) :: t0,t1,t2,t3
        
        t0 = u%d%f**v%d%f
        t1 = log(u%d%f)
        t2 = 1.0_${real_kind}$/u%d%f
        t3 = t1*v%d%f + 1
        res%d%f = t0
        res%d%g = t0*(t1*v%d%g + t2*u%d%g*v%d%f)
        k = 0
        do j = 1, size(res%d%g)
            do i = j, size(res%d%g)
                k = k + 1
                res%h(k) = t0*(t1*v%h(k) + t2*u%h(k)*v%d%f + t2*u%d%g(j)*(t2*u%d%g(i)*v%d%f*(v%d%f - 1 &
      ) + t3*v%d%g(i)) + v%d%g(j)*(t1**2*v%d%g(i) + t2*t3*u%d%g(i)))
            end do
        end do
      #:if test_coverage
        pow_hd_hd_counter = pow_hd_hd_counter + 1
      #:endif
    end function
#:enddef

