
#:def sqrt_d(dual_type, dual_sn, real_kind, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function sqrt__${dual_sn}$(u) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$) :: res
        real(${real_kind}$) :: t0
        
        t0 = sqrt(u%f)
        res%f = t0
        res%g = 0.5_${real_kind}$*u%g/t0
      #:if test_coverage
        sqrt_d_counter = sqrt_d_counter + 1
      #:endif
    end function
#:enddef

#:def sqrt_hd(dual_type, dual_sn, real_kind, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function sqrt__${dual_sn}$(u) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$) :: res
        integer :: i, j, k
        real(${real_kind}$) :: t0,t1
        
        t0 = sqrt(u%d%f)
        t1 = 1.0_${real_kind}$/t0
        res%d%f = t0
        res%d%g = 0.5_${real_kind}$*t1*u%d%g
        k = 0
        do j = 1, size(res%d%g)
            do i = j, size(res%d%g)
                k = k + 1
                res%h(k) = (0.25_${real_kind}$)*t1*(2*u%h(k) - u%d%g(i)*u%d%g(j)/u%d%f)
            end do
        end do
      #:if test_coverage
        sqrt_hd_counter = sqrt_hd_counter + 1
      #:endif
    end function
#:enddef

