
#:def add_d(dual_type, dual_sn, real_kind, size_dx, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function unary_add_${dual_sn}$(u) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$) :: res
        
        res%x = u%x
        res%dx = u%dx
      #:if test_coverage
        unary_add_${dual_sn}$_counter = unary_add_${dual_sn}$_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function add_${dual_sn}$_${dual_sn}$(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u%x + v%x
        res%dx = u%dx + v%dx
      #:if test_coverage
        add_${dual_sn}$_${dual_sn}$_counter = add_${dual_sn}$_${dual_sn}$_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function add_${dual_sn}$_r(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        real(${real_kind}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u%x + v
        res%dx = u%dx
      #:if test_coverage
        add_${dual_sn}$_r_counter = add_${dual_sn}$_r_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function add_r_${dual_sn}$(u, v) result(res)
        real(${real_kind}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u + v%x
        res%dx = v%dx
      #:if test_coverage
        add_r_${dual_sn}$_counter = add_r_${dual_sn}$_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function add_${dual_sn}$_i(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        integer, intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u%x + v
        res%dx = u%dx
      #:if test_coverage
        add_${dual_sn}$_i_counter = add_${dual_sn}$_i_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function add_i_${dual_sn}$(u, v) result(res)
        integer, intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u + v%x
        res%dx = v%dx
      #:if test_coverage
        add_i_${dual_sn}$_counter = add_i_${dual_sn}$_counter + 1
      #:endif
    end function
#:enddef

#:def add_hd(dual_type, dual_sn, real_kind, size_dx, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function unary_add_${dual_sn}$(u) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$) :: res
        
        res%x = u%x
        res%dx = u%dx
        res%ddx = u%ddx
      #:if test_coverage
        unary_add_${dual_sn}$_counter = unary_add_${dual_sn}$_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function add_${dual_sn}$_${dual_sn}$(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u%x + v%x
        res%dx = u%dx + v%dx
        res%ddx = u%ddx + v%ddx
      #:if test_coverage
        add_${dual_sn}$_${dual_sn}$_counter = add_${dual_sn}$_${dual_sn}$_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function add_${dual_sn}$_r(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        real(${real_kind}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u%x + v
        res%dx = u%dx
        res%ddx = u%ddx
      #:if test_coverage
        add_${dual_sn}$_r_counter = add_${dual_sn}$_r_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function add_r_${dual_sn}$(u, v) result(res)
        real(${real_kind}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u + v%x
        res%dx = v%dx
        res%ddx = v%ddx
      #:if test_coverage
        add_r_${dual_sn}$_counter = add_r_${dual_sn}$_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function add_${dual_sn}$_i(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        integer, intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u%x + v
        res%dx = u%dx
        res%ddx = u%ddx
      #:if test_coverage
        add_${dual_sn}$_i_counter = add_${dual_sn}$_i_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function add_i_${dual_sn}$(u, v) result(res)
        integer, intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u + v%x
        res%dx = v%dx
        res%ddx = v%ddx
      #:if test_coverage
        add_i_${dual_sn}$_counter = add_i_${dual_sn}$_counter + 1
      #:endif
    end function
#:enddef

