#:def div_d(dual_type, real_kind, is_pure=True, test_coverage=False)
    #!set elemental_purity = dnad.elemental_purity(is_pure, test_coverage)
    ${elemental_purity}$ function div_d_d(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        res%x = u%x/v%x
        res%dx = u%dx/v%x - u%x*v%dx/v%x**2
      #:if test_coverage == True
        div_d_d_counter = div_d_d_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function div_d_r(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        real(${real_kind}$), intent(in) :: v
        type(${dual_type}$) :: res
        res%x = u%x/v
        res%dx = u%dx/v
      #:if test_coverage == True
        div_d_r_counter = div_d_r_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function div_r_d(u, v) result(res)
        real(${real_kind}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        res%x = u/v%x
        res%dx = -u*v%dx/v%x**2
      #:if test_coverage == True
        div_r_d_counter = div_r_d_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function div_d_i(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        integer, intent(in) :: v
        type(${dual_type}$) :: res
        res%x = u%x/v
        res%dx = u%dx/v
      #:if test_coverage == True
        div_d_i_counter = div_d_i_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function div_i_d(u, v) result(res)
        integer, intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        res%x = u/v%x
        res%dx = -u*v%dx/v%x**2
      #:if test_coverage == True
        div_i_d_counter = div_i_d_counter + 1
      #:endif
    end function
#:enddef
#:def div_hd(dual_type, real_kind, is_pure=True, test_coverage=False)
    #!set elemental_purity = dnad.elemental_purity(is_pure, test_coverage)
    ${elemental_purity}$ function div_hd_hd(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        integer :: j
        res%x = u%x/v%x
        res%dx = u%dx/v%x - u%x*v%dx/v%x**2
        do j = 1, ${number_of_derivatives}$
            res%ddx(:, j) = u%ddx(:, j)/v%x - u%dx(j)*v%dx/v%x**2 - u%x*v%ddx(:, j)/v%x**2 + &
      v%dx(j)*(-u%dx/v%x**2 + 2*u%x*v%dx/v%x**3)
        end do
      #:if test_coverage == True
        div_hd_hd_counter = div_hd_hd_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function div_hd_r(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        real(${real_kind}$), intent(in) :: v
        type(${dual_type}$) :: res
        integer :: j
        res%x = u%x/v
        res%dx = u%dx/v
        do j = 1, ${number_of_derivatives}$
            res%ddx(:, j) = u%ddx(:, j)/v
        end do
      #:if test_coverage == True
        div_hd_r_counter = div_hd_r_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function div_r_hd(u, v) result(res)
        real(${real_kind}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        integer :: j
        res%x = u/v%x
        res%dx = -u*v%dx/v%x**2
        do j = 1, ${number_of_derivatives}$
            res%ddx(:, j) = -u*v%ddx(:, j)/v%x**2 + 2*u*v%dx*v%dx(j)/v%x**3
        end do
      #:if test_coverage == True
        div_r_hd_counter = div_r_hd_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function div_hd_i(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        integer, intent(in) :: v
        type(${dual_type}$) :: res
        integer :: j
        res%x = u%x/v
        res%dx = u%dx/v
        do j = 1, ${number_of_derivatives}$
            res%ddx(:, j) = u%ddx(:, j)/v
        end do
      #:if test_coverage == True
        div_hd_i_counter = div_hd_i_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function div_i_hd(u, v) result(res)
        integer, intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        integer :: j
        res%x = u/v%x
        res%dx = -u*v%dx/v%x**2
        do j = 1, ${number_of_derivatives}$
            res%ddx(:, j) = -u*v%ddx(:, j)/v%x**2 + 2*u*v%dx*v%dx(j)/v%x**3
        end do
      #:if test_coverage == True
        div_i_hd_counter = div_i_hd_counter + 1
      #:endif
    end function
#:enddef
