
#:def gt(dual_type, real_kind, is_pure, test_coverage, dual_short_name)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$  function gt_${dual_short_name}$_${dual_short_name}$(lhs, rhs) result(res)
         type(${dual_type}$), intent(in) :: lhs, rhs
         logical :: res

         res = (lhs%x > rhs%x)

    end function
    ${elemental_purity}$  function gt_${dual_short_name}$_i(lhs, rhs) result(res)
         type(${dual_type}$), intent(in) :: lhs
         integer, intent(in) :: rhs
         logical :: res

         res = (lhs%x > rhs)

    end function
    ${elemental_purity}$  function gt_${dual_short_name}$_r(lhs, rhs) result(res)
         type(${dual_type}$), intent(in) :: lhs
         real(${real_kind}$), intent(in) :: rhs
         logical :: res

         res = (lhs%x > rhs)

    end function
    ${elemental_purity}$  function gt_i_${dual_short_name}$(lhs, rhs) result(res)
         integer, intent(in) :: lhs
         type(${dual_type}$), intent(in) :: rhs
         logical :: res

         res = (lhs > rhs%x)

    end function
    ${elemental_purity}$  function gt_r_${dual_short_name}$(lhs, rhs) result(res)
         real(${real_kind}$), intent(in) :: lhs
         type(${dual_type}$), intent(in) :: rhs
         logical :: res

         res = (lhs > rhs%x)

    end function
#:enddef
