#:def initialize_d(dual_type, dual_sn, real_kind)
    pure subroutine initialize_${dual_sn}$(dual, val, idiff)
        type(${dual_type}$), intent(out) :: dual
        real(${real_kind}$), intent(in) :: val
        integer, intent(in) :: idiff
        
        dual%x = val
        dual%dx = 0
        dual%dx(idiff) = 1

    end subroutine
#:enddef

#:def initialize_hd(dual_type, dual_sn, real_kind)
    pure subroutine initialize_${dual_sn}$(hdual, val, idiff)
        type(${dual_type}$), intent(out) :: hdual
        real(${real_kind}$), intent(in) :: val
        integer, intent(in) :: idiff
        
        hdual%x = val
        hdual%dx = 0
        hdual%ddx = 0
        hdual%dx(idiff) = 1

    end subroutine
#:enddef
