
#:def minus_d(dual_type, real_kind, size_dx, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function unary_minus_d(u) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$) :: res
        
        res%x = -u%x
        res%dx = -u%dx
      #:if test_coverage
        unary_minus_d_counter = unary_minus_d_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_d_d(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u%x - v%x
        res%dx = u%dx - v%dx
      #:if test_coverage
        minus_d_d_counter = minus_d_d_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_d_r(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        real(${real_kind}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u%x - v
        res%dx = u%dx
      #:if test_coverage
        minus_d_r_counter = minus_d_r_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_r_d(u, v) result(res)
        real(${real_kind}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u - v%x
        res%dx = -v%dx
      #:if test_coverage
        minus_r_d_counter = minus_r_d_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_d_i(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        integer, intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u%x - v
        res%dx = u%dx
      #:if test_coverage
        minus_d_i_counter = minus_d_i_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_i_d(u, v) result(res)
        integer, intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u - v%x
        res%dx = -v%dx
      #:if test_coverage
        minus_i_d_counter = minus_i_d_counter + 1
      #:endif
    end function
#:enddef

#:def minus_hd(dual_type, real_kind, size_dx, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function unary_minus_hd(u) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$) :: res
        
        res%x = -u%x
        res%dx = -u%dx
        res%ddx = -u%ddx
      #:if test_coverage
        unary_minus_hd_counter = unary_minus_hd_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_hd_hd(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u%x - v%x
        res%dx = u%dx - v%dx
        res%ddx = u%ddx - v%ddx
      #:if test_coverage
        minus_hd_hd_counter = minus_hd_hd_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_hd_r(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        real(${real_kind}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u%x - v
        res%dx = u%dx
        res%ddx = u%ddx
      #:if test_coverage
        minus_hd_r_counter = minus_hd_r_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_r_hd(u, v) result(res)
        real(${real_kind}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u - v%x
        res%dx = -v%dx
        res%ddx = -v%ddx
      #:if test_coverage
        minus_r_hd_counter = minus_r_hd_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_hd_i(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        integer, intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u%x - v
        res%dx = u%dx
        res%ddx = u%ddx
      #:if test_coverage
        minus_hd_i_counter = minus_hd_i_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_i_hd(u, v) result(res)
        integer, intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u - v%x
        res%dx = -v%dx
        res%ddx = -v%ddx
      #:if test_coverage
        minus_i_hd_counter = minus_i_hd_counter + 1
      #:endif
    end function
#:enddef

