
#:def minus_d(dual_type, dual_sn, real_kind, size_dx, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function unary_minus_${dual_sn}$(u) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$) :: res
        
        res%x = -u%x
        res%dx = -u%dx
      #:if test_coverage
        unary_minus_${dual_sn}$_counter = unary_minus_${dual_sn}$_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_${dual_sn}$_${dual_sn}$(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u%x - v%x
        res%dx = u%dx - v%dx
      #:if test_coverage
        minus_${dual_sn}$_${dual_sn}$_counter = minus_${dual_sn}$_${dual_sn}$_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_${dual_sn}$_r(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        real(${real_kind}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u%x - v
        res%dx = u%dx
      #:if test_coverage
        minus_${dual_sn}$_r_counter = minus_${dual_sn}$_r_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_r_${dual_sn}$(u, v) result(res)
        real(${real_kind}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u - v%x
        res%dx = -v%dx
      #:if test_coverage
        minus_r_${dual_sn}$_counter = minus_r_${dual_sn}$_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_${dual_sn}$_i(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        integer, intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u%x - v
        res%dx = u%dx
      #:if test_coverage
        minus_${dual_sn}$_i_counter = minus_${dual_sn}$_i_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_i_${dual_sn}$(u, v) result(res)
        integer, intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u - v%x
        res%dx = -v%dx
      #:if test_coverage
        minus_i_${dual_sn}$_counter = minus_i_${dual_sn}$_counter + 1
      #:endif
    end function
#:enddef

#:def minus_hd(dual_type, dual_sn, real_kind, size_dx, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function unary_minus_${dual_sn}$(u) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$) :: res
        
        res%x = -u%x
        res%dx = -u%dx
        res%ddx = -u%ddx
      #:if test_coverage
        unary_minus_${dual_sn}$_counter = unary_minus_${dual_sn}$_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_${dual_sn}$_${dual_sn}$(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u%x - v%x
        res%dx = u%dx - v%dx
        res%ddx = u%ddx - v%ddx
      #:if test_coverage
        minus_${dual_sn}$_${dual_sn}$_counter = minus_${dual_sn}$_${dual_sn}$_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_${dual_sn}$_r(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        real(${real_kind}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u%x - v
        res%dx = u%dx
        res%ddx = u%ddx
      #:if test_coverage
        minus_${dual_sn}$_r_counter = minus_${dual_sn}$_r_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_r_${dual_sn}$(u, v) result(res)
        real(${real_kind}$), intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u - v%x
        res%dx = -v%dx
        res%ddx = -v%ddx
      #:if test_coverage
        minus_r_${dual_sn}$_counter = minus_r_${dual_sn}$_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_${dual_sn}$_i(u, v) result(res)
        type(${dual_type}$), intent(in) :: u
        integer, intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u%x - v
        res%dx = u%dx
        res%ddx = u%ddx
      #:if test_coverage
        minus_${dual_sn}$_i_counter = minus_${dual_sn}$_i_counter + 1
      #:endif
    end function
    ${elemental_purity}$ function minus_i_${dual_sn}$(u, v) result(res)
        integer, intent(in) :: u
        type(${dual_type}$), intent(in) :: v
        type(${dual_type}$) :: res
        
        res%x = u - v%x
        res%dx = -v%dx
        res%ddx = -v%ddx
      #:if test_coverage
        minus_i_${dual_sn}$_counter = minus_i_${dual_sn}$_counter + 1
      #:endif
    end function
#:enddef

