
#:def sqrt_d(dual_type, dual_sn, real_kind, size_dx, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function sqrt_${dual_sn}$(u) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$) :: res
        real(${real_kind}$) :: t0
        
        t0 = sqrt(u%x)
        res%x = t0
        res%dx = 0.5_${real_kind}$*u%dx/t0
      #:if test_coverage
        sqrt_${dual_sn}$_counter = sqrt_${dual_sn}$_counter + 1
      #:endif
    end function
#:enddef

#:def sqrt_hd(dual_type, dual_sn, real_kind, size_dx, is_pure, test_coverage)
    #:if is_pure and not test_coverage
        #:set elemental_purity = "elemental"
    #:else
        #:set elemental_purity = "impure elemental"
    #:endif
    ${elemental_purity}$ function sqrt_${dual_sn}$(u) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$) :: res
        integer :: i, j, k
        real(${real_kind}$) :: t0,t1
        
        t0 = sqrt(u%x)
        t1 = 1.0_${real_kind}$/t0
        res%x = t0
        res%dx = 0.5_${real_kind}$*t1*u%dx
        k = 0
        do j = 1, ${size_dx}$
            do i = j, ${size_dx}$
                k = k + 1
                res%ddx(k) = (0.25_${real_kind}$)*t1*(2*u%ddx(k) - u%dx(i)*u%dx(j)/u%x)
            end do
        end do
      #:if test_coverage
        sqrt_${dual_sn}$_counter = sqrt_${dual_sn}$_counter + 1
      #:endif
    end function
#:enddef

