#:def sqrt_d(dual_type, real_kind)
    ${elemental_purity}$ function sqrt_d(u) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$) :: res
        res%x = sqrt(u%x)
        res%dx = 0.5_${real_kind}$*u%dx/sqrt(u%x)
      #:if test_coverage == True
        sqrt_d_counter = sqrt_d_counter + 1
      #:endif
    end function
#:enddef
#:def sqrt_hd(dual_type, real_kind)
    ${elemental_purity}$ function sqrt_hd(u) result(res)
        type(${dual_type}$), intent(in) :: u
        type(${dual_type}$) :: res
        integer :: j
        res%x = sqrt(u%x)
        res%dx = 0.5_${real_kind}$*u%dx/sqrt(u%x)
        do j = 1, ${number_of_derivatives}$
            res%ddx(:, j) = 0.5_${real_kind}$*u%ddx(:, j)/sqrt(u%x) - 0.25_${real_kind}$*u%dx*u%dx(j)/ &
      u%x**1.5_${real_kind}$
        end do
      #:if test_coverage == True
        sqrt_hd_counter = sqrt_hd_counter + 1
      #:endif
    end function
#:enddef
