#:def dnad_dual_type(dual_type, real_kind, number_of_derivatives, statement)

    type :: ${dual_type}$
        #! statement can for instance be 'sequence' or nothing
        #!   the original dnad code had 'sequence' here, but I dont know what it is good for...
        ${statement}$
        real(${real_kind}$) :: x  ! functional value
        real(${real_kind}$) :: dx(${number_of_derivatives}$)  ! derivative
    end type

#:enddef
