#:def dnad_dual_type(dual_type, real_kind, number_of_derivatives, statement, ddual_type=None)

    type :: ${dual_type}$
        !! dual number type
        #! statement can for instance be 'sequence' or nothing
        #!   the original dnad code had 'sequence' here, but I dont know what it is good for...
        ${statement}$
        real(${real_kind}$) :: x  ! functional value
        real(${real_kind}$) :: dx(${number_of_derivatives}$)  ! derivative
    end type

  #:if ddual_type is not None
    type :: ${ddual_type}$
        !! double dual number type with dual dx component
        #! statement can for instance be 'sequence' or nothing
        #!   the original dnad code had 'sequence' here, but I dont know what it is good for...
        ${statement}$
        real(${real_kind}$) :: x  ! functional value
        type(${dual_type}$) :: dx(${number_of_derivatives}$)  ! derivative
    end type
  #:endif

#:enddef
