#:def dnad_dual_type(type_spec, real_kind, size_dx, statement = "")
    #:set type_suffix, has_hdual = dnad.decode_type_spec(type_spec)
    type :: dual__${type_suffix}$_t
        !! dual number type
        ${statement}$
        real(${real_kind}$) :: f = 0  ! functional value
        real(${real_kind}$) :: g(${size_dx}$) = 0  ! derivatives
    end type
  #:if has_hdual
    type :: hdual__${type_suffix}$_t
        !! hyper-dual number type
        ${statement}$
        type(dual__${type_suffix}$_t) :: d  ! dual number
        real(${real_kind}$) :: h(${size_dx}$*(${size_dx}$ + 1)/2) = 0  ! Lower triangular of Hessian
    end type
  #:endif
#:enddef
