#:def dnad_dual_type(dual_type, real_kind, size_dx, statement)
    type :: ${dual_type}$
        !! dual number type
        #! statement can for instance be 'sequence' or nothing
        #!   the original dnad code had 'sequence' here, but I dont know what it is good for...
        ${statement}$
        real(${real_kind}$) :: f = 0  ! functional value
        real(${real_kind}$) :: g(${size_dx}$) = 0  ! derivatives
    end type
#:enddef

#:def dnad_hdual_type(dual_type, real_kind, size_dx, statement)
    type :: ${dual_type}$
        !! hyper-dual number type
        #! statement can for instance be 'sequence' or nothing
        #!   the original dnad code had 'sequence' here, but I dont know what it is good for...
        ${statement}$
        real(${real_kind}$) :: f = 0  ! functional value
        real(${real_kind}$) :: g(${size_dx}$) = 0  ! derivatives
        real(${real_kind}$) :: h(${size_dx}$*(${size_dx}$ + 1)/2) = 0  ! Lower triangular of Hessian
    end type
#:enddef
