#:def dnad_interfaces(selected_interfaces, has_dual=False, has_hyper_dual=False) 
    #!
    #:assert has_dual or has_hyper_dual
    #!
    #:set interface_list = dnad.select_interfaces(selected_interfaces)
    #!
  #:if has_hyper_dual
    interface hessian ! Extract Hessian from a hyper-dual number
        module procedure hessian_matrix
    end interface
  #:endif

  #:if "=" in interface_list 
    interface assignment (=)
      #:if has_dual
        module procedure assign_d_i  ! dual=integer, elemental
        module procedure assign_d_r  ! dual=real, elemental
        module procedure assign_i_d  ! integer=dual, elemental
        module procedure assign_r_d  ! real=dual, elemental
      #:endif
      #:if has_hyper_dual
        module procedure assign_hd_i  ! dual=integer, elemental
        module procedure assign_hd_r  ! dual=real, elemental
        module procedure assign_i_hd  ! integer=dual, elemental
        module procedure assign_r_hd  ! real=dual, elemental
      #:endif
    end interface
  #:endif 
  #:if "+" in interface_list 
    interface operator (+)
      #:if has_dual
        module procedure unary_add_d   ! +dual number, elemental
        module procedure add_d_d       ! dual + dual, elemental
        module procedure add_d_i       ! dual + integer, elemental
        module procedure add_d_r       ! dual + real, elemental
        module procedure add_i_d       ! integer + dual, elemental
        module procedure add_r_d       ! real + dual, elemental
      #:endif
      #:if has_hyper_dual
        module procedure unary_add_hd  ! +dual number, elemental
        module procedure add_hd_hd     ! dual + dual, elemental
        module procedure add_hd_i      ! dual + integer, elemental
        module procedure add_hd_r      ! dual + real, elemental
        module procedure add_i_hd      ! integer + dual, elemental
        module procedure add_r_hd      ! real + dual, elemental
      #:endif
    end interface
  #:endif 
  #:if "-" in interface_list 
    interface operator (-)
      #:if has_dual
        module procedure unary_minus_d  ! negate a dual number,elemental
        module procedure minus_d_d      ! dual -dual,elemental
        module procedure minus_d_i      ! dual-integer,elemental
        module procedure minus_d_r      ! dual-real,elemental
        module procedure minus_i_d      ! integer-dual,elemental
        module procedure minus_r_d      ! real-dual,elemental
      #:endif
      #:if has_hyper_dual
        module procedure unary_minus_hd ! negate a dual number,elemental
        module procedure minus_hd_hd    ! dual -dual,elemental
        module procedure minus_hd_i     ! dual-integer,elemental
        module procedure minus_hd_r     ! dual-real,elemental
        module procedure minus_i_hd     ! integer-dual,elemental
        module procedure minus_r_hd     ! real-dual,elemental
      #:endif
    end interface
  #:endif 
  #:if "*" in interface_list 
    interface operator (*)
      #:if has_dual 
        module procedure mult_d_d    ! dual*dual, elemental
        module procedure mult_d_i    ! dual*integer,elemental
        module procedure mult_d_r    ! dual*real,elemental
        module procedure mult_i_d    ! integer*dual,elemental
        module procedure mult_r_d    ! real*dual,elemental
      #:endif
      #:if has_hyper_dual
        module procedure mult_hd_hd  ! dual*dual, elemental
        module procedure mult_hd_i   ! dual*integer,elemental
        module procedure mult_hd_r   ! dual*real,elemental
        module procedure mult_i_hd   ! integer*dual,elemental
        module procedure mult_r_hd   ! real*dual,elemental
      #:endif
    end interface
  #:endif 
  #:if "/" in interface_list 
    interface operator (/)
      #:if has_dual
        module procedure div_d_d    ! dual/dual, elemental
        module procedure div_d_r    ! dual/real, elemental
        module procedure div_r_d    ! real/dual, elemental
        module procedure div_d_i    ! dual/integer, elemental
        module procedure div_i_d    ! integer/dual, elemental
      #:endif
      #:if has_hyper_dual
        module procedure div_hd_hd  ! hdual/hdual, elemental
        module procedure div_hd_r   ! hdual/real, elemental
        module procedure div_r_hd   ! real/hdual, elemental
        module procedure div_hd_i   ! hdual/integer, elemental
        module procedure div_i_hd   ! integer/hdual, elemental
      #:endif
    end interface
  #:endif 
  #:if "**" in interface_list 
    interface operator (**)
      #:if has_dual
        module procedure pow_d_i ! dual number to an integer power,elemental
        module procedure pow_d_r ! dual number to a real power, elemental
        module procedure pow_d_d ! dual number to a dual power, elemental
      #:endif
      #:if has_hyper_dual
        module procedure pow_hd_i ! hdual number to an integer power,elemental
        module procedure pow_hd_r ! hdual number to a real power, elemental
        module procedure pow_hd_hd ! hdual number to a hdual power, elemental
      #:endif
    end interface
  #:endif 
  #:if "==" in interface_list 
    interface operator (==)
      #:if has_dual
        module procedure eq_d_d ! compare two dual numbers, elemental
        module procedure eq_d_i ! compare a dual and an integer, elemental
        module procedure eq_d_r ! compare a dual and a real, elemental
        module procedure eq_i_d ! compare integer with a dual number, elemental
        module procedure eq_r_d ! compare a real with a dual number, elemental
      #:endif
      #:if has_hyper_dual
        module procedure eq_hd_hd ! compare two hdual numbers, elemental
        module procedure eq_hd_i ! compare a hdual and an integer, elemental
        module procedure eq_hd_r ! compare a hdual and a real, elemental
        module procedure eq_i_hd ! compare integer with a hdual number, elemental
        module procedure eq_r_hd ! compare a real with a hdual number, elemental
      #:endif
    end interface
  #:endif 
  #:if "<=" in interface_list 
    interface operator (<=)
      #:if has_dual
        module procedure le_d_d ! compare two dual numbers, elemental
        module procedure le_d_i ! compare a dual and an integer, elemental
        module procedure le_d_r ! compare a dual and a real, elemental
        module procedure le_i_d ! compare integer with a dual number, elemental
        module procedure le_r_d ! compare a real with a dual number, elemental
      #:endif
      #:if has_hyper_dual
        module procedure le_hd_hd ! compare two hdual numbers, elemental
        module procedure le_hd_i ! compare a hdual and an integer, elemental
        module procedure le_hd_r ! compare a hdual and a real, elemental
        module procedure le_i_hd ! compare integer with a hdual number, elemental
        module procedure le_r_hd ! compare a real with a hdual number, elemental
      #:endif
    end interface
  #:endif 
  #:if "<" in interface_list 
    interface operator (<)
      #:if has_dual
        module procedure lt_d_d ! compare two dual numbers, elemental
        module procedure lt_d_i ! compare a dual and an integer, elemental
        module procedure lt_d_r ! compare a dual and a real, elemental
        module procedure lt_i_d ! compare integer with a dual number, elemental
        module procedure lt_r_d ! compare a real with a dual number, elemental
      #:endif
      #:if has_hyper_dual
        module procedure lt_hd_hd ! compare two hdual numbers, elemental
        module procedure lt_hd_i ! compare a hdual and an integer, elemental
        module procedure lt_hd_r ! compare a hdual and a real, elemental
        module procedure lt_i_hd ! compare integer with a hdual number, elemental
        module procedure lt_r_hd ! compare a real with a hdual number, elemental
      #:endif
    end interface
  #:endif 
  #:if ">=" in interface_list 
    interface operator (>=)
      #:if has_dual
        module procedure ge_d_d ! compare two dual numbers, elemental
        module procedure ge_d_i ! compare a dual and an integer, elemental
        module procedure ge_d_r ! compare a dual and a real, elemental
        module procedure ge_i_d ! compare integer with a dual number, elemental
        module procedure ge_r_d ! compare a real with a dual number, elemental
      #:endif
      #:if has_hyper_dual
        module procedure ge_hd_hd ! compare two hdual numbers, elemental
        module procedure ge_hd_i ! compare a hdual and an integer, elemental
        module procedure ge_hd_r ! compare a hdual and a real, elemental
        module procedure ge_i_hd ! compare integer with a hdual number, elemental
        module procedure ge_r_hd ! compare a real with a hdual number, elemental
      #:endif
    end interface
  #:endif 
  #:if ">" in interface_list 
    interface operator (>)
      #:if has_dual
        module procedure gt_d_d ! compare two dual numbers, elemental
        module procedure gt_d_i ! compare a dual and an integer, elemental
        module procedure gt_d_r ! compare a dual and a real, elemental
        module procedure gt_i_d ! compare integer with a dual number, elemental
        module procedure gt_r_d ! compare a real with a dual number, elemental
      #:endif
      #:if has_hyper_dual
        module procedure gt_hd_hd ! compare two hdual numbers, elemental
        module procedure gt_hd_i ! compare a hdual and an integer, elemental
        module procedure gt_hd_r ! compare a hdual and a real, elemental
        module procedure gt_i_hd ! compare integer with a hdual number, elemental
        module procedure gt_r_hd ! compare a real with a hdual number, elemental
      #:endif
    end interface
  #:endif 
  #:if "/=" in interface_list 
    interface operator (/=)
      #:if has_dual
        module procedure ne_d_d ! compare two dual numbers, elemental
        module procedure ne_d_i ! compare a dual and an integer, elemental
        module procedure ne_d_r ! compare a dual and a real, elemental
        module procedure ne_i_d ! compare integer with a dual number, elemental
        module procedure ne_r_d ! compare a real with a dual number, elemental
      #:endif
      #:if has_hyper_dual
        module procedure ne_hd_hd ! compare two hdual numbers, elemental
        module procedure ne_hd_i ! compare a hdual and an integer, elemental
        module procedure ne_hd_r ! compare a hdual and a real, elemental
        module procedure ne_i_hd ! compare integer with a hdual number, elemental
        module procedure ne_r_hd ! compare a real with a hdual number, elemental
      #:endif
    end interface
  #:endif 
  #:if "abs" in interface_list 
    interface abs
        module procedure abs_d  ! absolute value of a dual number, elemental
    end interface
  #:endif 
  #:if "dabs" in interface_list 
    interface dabs
        module procedure abs_d ! same as abs, used for some old fortran commands
    end interface
  #:endif 
  #:if "acos" in interface_list 
    interface acos
        module procedure acos_d ! arccosine of a dual number, elemental
    end interface
  #:endif 
  #:if "asin" in interface_list 
    interface asin
        module procedure asin_d ! arcsine of a dual number, elemental
    end interface
  #:endif 
  #:if "atan" in interface_list 
    interface atan
        module procedure atan_d ! arctan of a dual number, elemental
    end interface
  #:endif 
  #:if "atan2" in interface_list 
    interface atan2
        module procedure atan2_d ! arctan of a dual number, elemental
    end interface
  #:endif 
  #:if "cos" in interface_list 
    interface cos
        module procedure cos_d ! cosine of a dual number, elemental
    end interface
  #:endif 
  #:if "dcos" in interface_list 
    interface dcos
        module procedure cos_d ! cosine of a dual number, elemental
    end interface
  #:endif 
  #:if "dot_product" in interface_list 
    interface dot_product
        module procedure dot_product_dd ! dot product two dual number vectors
    end interface
  #:endif 
  #:if "exp" in interface_list 
    interface exp
        module procedure exp_d ! exponential of a dual number, elemental
    end interface
  #:endif 
  #:if "int" in interface_list 
    interface int
        module procedure int_d ! integer part of a dual number, elemental
    end interface
  #:endif 
  #:if "log" in interface_list 
    interface log
      #:if has_dual
        module procedure log_d ! log of a dual number, elemental
      #:endif
      #:if has_hyper_dual 
        module procedure log_hd ! log of a dual number, elemental
      #:endif
    end interface
  #:endif 
  #:if "log10" in interface_list 
    interface log10
        module procedure log10_d ! log of a dual number, elemental
    end interface
  #:endif 
  #:if "matmul" in interface_list 
    interface matmul
        module procedure matmul_dd ! multiply two dual matrices
        module procedure matmul_dv ! multiply a dual matrix with a dual vector
        module procedure matmul_vd ! multiply a dual vector with a dual matrix
    end interface
  #:endif 
  #:if "max" in interface_list 
    interface max
        module procedure max_dd ! max of two dual numbers, elemental
        module procedure max_di ! max of a dual number and an integer, elemental
        module procedure max_dr ! max of a dual number and a real, elemental
        module procedure max_rd ! max of a real,and a dual number,  elemental
    end interface
  #:endif 
  #:if "dmax1" in interface_list 
    interface dmax1
        module procedure dmax1_dd ! max of from two to four dual numbers, elemental
    end interface
  #:endif 
  #:if "maxval" in interface_list 
    interface maxval
        module procedure maxval_d ! maxval of a dual number vector
    end interface
  #:endif 
  #:if "min" in interface_list 
    interface min
        module procedure min_dd ! min of from two to four dual numbers, elemental
        module procedure min_dr ! min of a dual and a real, elemental
    end interface
  #:endif 
  #:if "dmin1" in interface_list 
    interface dmin1
        module procedure dmin1_dd ! min of from two to four dual numbers, elemental
    end interface
  #:endif 
  #:if "minval" in interface_list 
    interface minval
        module procedure minval_d ! obtain the maxval  of a dual number vectgor
    end interface
  #:endif 
  #:if "nint" in interface_list 
    interface nint
        module procedure nint_d ! nearest integer to the argument, elemental
    end interface
  #:endif 
  #:if "sign" in interface_list 
    interface  sign
      module procedure  sign_dd ! sign(a,b) with two dual numbers, elemental
      module procedure  sign_rd ! sign(a,b) with a real and a dual, elemental
    end interface
  #:endif 
  #:if "sin" in interface_list 
    interface sin
        module procedure sin_d ! obtain sine of a dual number, elemental
    end interface
  #:endif 
  #:if "dsin" in interface_list 
    interface dsin
        module procedure sin_d ! obtain sine of a dual number, elemental
    end interface
  #:endif 
  #:if "tan" in interface_list 
    interface tan
        module procedure tan_d ! obtain sine of a dual number, elemental
    end interface
  #:endif 
  #:if "dtan" in interface_list 
    interface dtan
        module procedure tan_d ! obtain sine of a dual number, elemental
    end interface
  #:endif 
  #:if "sqrt" in interface_list 
    interface sqrt
      #:if has_dual
        module procedure sqrt_d ! obtain the sqrt of a dual number, elemental
      #:endif
      #:if has_hyper_dual 
        module procedure sqrt_hd ! obtain the sqrt of a dual number, elemental
      #:endif
    end interface
  #:endif 
  #:if "sum" in interface_list 
    interface sum
        module procedure sum_d ! sum a dual array
    end interface
  #:endif 
  #:if "maxloc" in interface_list 
    interface maxloc
        module procedure maxloc_d ! location of max in a dual array
    end interface
  #:endif 
#:enddef 
